### ISSUE TITLE
Getting error "Missing Mod Exception Clarity.esp"

### ISSUE THREAD

**Issue by dzee349** [Aurelianis/SynFO4LightingRegionCellPatcher#1]
Hi, Happy Holidays! First off, thank you so, so much for this patcher.  Looking forward to saving myself hours of manual work.  Unfortunately, when I attempt to run the patcher, it errors out after 1.5s and says "Missing Mod Exception Clarity.esp".  I don't use Clarity, JSRS Sound Mod or David Hunter, but I use Ultra Interior Lighting and See Region Names on Your Save Files.

`No extra data to consider
Compiling
("X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Git\skpmqv0v.drt\Runner\LightingAndRegionPatcher"): "dotnet" "build \"LightingAndRegionPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "960f01bb0c01abd50701ba1dfa60836f16e5f5bd"
Running
(""): "dotnet" "run --project \"X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Git\skpmqv0v.drt\Runner\LightingAndRegionPatcher\LightingAndRegionPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"G:\SteamLibrary\steamapps\common\Fallout 4\Data\" --ExtraDataFolder \"H:\Non-Games\Synthesis\Data\Fallout 4\SynFO4LightingRegionCellPatcher\" --GameRelease Fallout4 --ModKey \"FO4 Lighting Region Cell Patcher.esp\" --LoadOrderFilePath \"X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Workspace\FO4 Lighting Region Cell Patcher\Plugins.txt\" --LoadOrderIncludesCreationClub --OutputPath \"X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Workspace\FO4 Lighting Region Cell Patcher\1 - SynFO4LightingRegionCellPatcher\FO4 Lighting Region Cell Patcher.esp\" --PatcherName SynFO4LightingRegionCellPatcher"
Mutagen version: 0.42
Mutagen sha: 4ad62460a9e5c6e3fc2ef68e2df0e10a014a4808
Synthesis version: 0.26
Synthesis sha: d4db80a931af636f5a507434220b07363355f719
Newtonsoft version: 13.0.3+0a2e291c0d9c0c7675d445703e51750363a549ef
run-patcher --DataFolderPath "G:\SteamLibrary\steamapps\common\Fallout 4\Data" --ExtraDataFolder "H:\Non-Games\Synthesis\Data\Fallout 4\SynFO4LightingRegionCellPatcher" --GameRelease Fallout4 --ModKey "FO4 Lighting Region Cell Patcher.esp" --LoadOrderFilePath "X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Workspace\FO4 Lighting Region Cell Patcher\Plugins.txt" --LoadOrderIncludesCreationClub --OutputPath "X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Workspace\FO4 Lighting Region Cell Patcher\1 - SynFO4LightingRegionCellPatcher\FO4 Lighting Region Cell Patcher.esp" --PatcherName SynFO4LightingRegionCellPatcher
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
CellPatcher - RunPatch - START
MissingModException Clarity.esp: Exception of type 'Mutagen.Bethesda.Plugins.Exceptions.MissingModException' was thrown.    at LightingAndRegionPatcher.Program.RunPatch(IPatcherState`2 state) in X:\Users\X\AppData\Local\Temp\Synthesis\obi0f1e0.dqq\Git\skpmqv0v.drt\Runner\LightingAndRegionPatcher\Program.cs:line 25
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass16_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 106
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 631
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456`

**Comment by Ghastly13** [comment]
Can confirm. It might be better to use modkeys for mod detection. Here's a great example: https://github.com/tr4wzified/AOSISCSoundPatcher
